### ISSUE TITLE
Approximate Entropy Test always fails

### ISSUE THREAD

**Issue by w1ldeFlow** [InsaneMonster/NistRng#2]
While using the package, I noticed that the approximate entropy test fails in every case I tried. While this may happen due to non-random data, I would have expected at least the benchmark example to pass.

Comparing test_approximate_entropy.py line 76 with the original NIST specification, the code should be `(math.log(2) - (phi_m[0] - phi_m[1]))` rather than `(math.log(2) - phi_m[0] - phi_m[1])` IMHO. Notice that the parentheses do change the meaning here because of the negative sign.

**Comment by InsaneMonster** [comment]
Thank you, I will fix.

**Comment by InsaneMonster** [comment]
Fixed as suggested. Will be available with the next version as soon as I have fixed other bugs. Thank you so much!
