### ISSUE TITLE
Cumulative Sums Test Missing in SP800_22R1A_BATTERY

### ISSUE THREAD

**Issue by w1ldeFlow** [InsaneMonster/NistRng#3]
The dictionary `SP800_22R1A_BATTERY`, defined on line 24 following of functions.py, contains only 14 tests and lacks the Cumulative Sums test.

Expected behavior is that `SP800_22R1A_BATTERY`contains all 15 tests of NIST SP800-22r1a.

**Comment by InsaneMonster** [comment]
I will check that out, thanks.

**Comment by InsaneMonster** [comment]
Fixed as suggested. Will be available with the next version as soon as I have fixed other bugs. Thank you so much!
