### ISSUE TITLE
Tests output error on large arrays

### ISSUE THREAD

**Issue by V-for-Vaggelis** [InsaneMonster/NistRng#5]
I have tried the tests with the code demonstrated in the benchmarks and  a numpy array of zeros and ones, while the the tests produce output for a arrays up to 800k elements they always return errors when I try this for a larger array (1 million elements or more).  Any idea why this is happening?

**Comment by InsaneMonster** [comment]
Thank you. Checked and fixed. There were some bugs for very large sequences and they should now be fixed. I will push the fixes within the next update.
